resolver: https://raw.githubusercontent.com/pgenie-io/stack-snapshot/aab5e5e5b06fcd71643997fe638323085adb1cff/snapshot.yaml
extra-deps:
  - git: https://github.com/pgenie-io/client
    commit: 36135c1f93ed0c8f77406356f86e3f230f01344d
